// TypeScript declarations for HTML Layout Parser WASM module
// Generated by Emscripten with custom extensions

export interface EmscriptenModule {
  // Memory management
  HEAPU8: Uint8Array;
  HEAP8: Int8Array;
  HEAP16: Int16Array;
  HEAP32: Int32Array;
  HEAPU16: Uint16Array;
  HEAPU32: Uint32Array;
  HEAPF32: Float32Array;
  HEAPF64: Float64Array;

  // Memory allocation
  _malloc(size: number): number;
  _free(ptr: number): void;

  // String utilities
  UTF8ToString(ptr: number, maxBytesToRead?: number): string;
  stringToUTF8(str: string, outPtr: number, maxBytesToWrite: number): void;
  lengthBytesUTF8(str: string): number;

  // Function calling utilities
  ccall(
    ident: string,
    returnType: string | null,
    argTypes: string[],
    args: any[]
  ): any;
  
  cwrap(
    ident: string,
    returnType: string | null,
    argTypes: string[]
  ): (...args: any[]) => any;

  // WASM exported functions
  _loadFont(fontDataPtr: number, fontDataSize: number, fontNamePtr: number): number;
  _unloadFont(fontId: number): number;
  _setDefaultFont(fontId: number): number;
  _getLoadedFonts(): number;
  _clearAllFonts(): number;
  
  _parseHTML(
    htmlPtr: number,
    cssPtr: number,
    viewportWidth: number,
    mode: number
  ): number;
  
  _parseHTMLWithDiagnostics(
    htmlPtr: number,
    cssPtr: number,
    viewportWidth: number,
    mode: number,
    enableMetrics: number
  ): number;
  
  _getLastParseResult(): number;
  _freeString(ptr: number): void;
  
  // Version and info
  _getVersion(): number;
  
  // Memory metrics
  _getMetrics(): number;
  _getDetailedMetrics(): number;
  _getTotalMemoryUsage(): number;
  _checkMemoryThreshold(): number;
  _getMemoryMetrics(): number;
  
  // Lifecycle
  _destroy(): void;
  
  // Debug
  _setDebugMode(enabled: number): void;
  _getDebugMode(): number;
  
  // Cache management
  _getCacheStats(): number;
  _resetCacheStats(): void;
  _clearCache(): void;

  // Module lifecycle
  onRuntimeInitialized?: () => void;
  ready: Promise<EmscriptenModule>;
}

// Factory function type
export interface ModuleFactory {
  (moduleOverrides?: Partial<EmscriptenModule>): Promise<EmscriptenModule>;
}

// Default export - the factory function
declare const createHtmlLayoutParserModule: ModuleFactory;
export default createHtmlLayoutParserModule;

// Named export for convenience
export { createHtmlLayoutParserModule };

// Additional type definitions for the high-level API
export interface CharLayout {
  character: string;
  x: number;
  y: number;
  width: number;
  height: number;
  baseline: number;
  fontSize: number;
  fontFamily: string;
  fontWeight: string;
  fontStyle: string;
  color: string;
  backgroundColor?: string;
  opacity: number;
  textDecoration?: {
    underline?: boolean;
    overline?: boolean;
    lineThrough?: boolean;
    color?: string;
    thickness?: number;
  };
}

export interface FontInfo {
  id: number;
  name: string;
  memoryUsage: number;
}

export interface MemoryMetrics {
  totalMemoryUsage: number;
  fontCount: number;
  fonts: FontInfo[];
}

export interface ParseOptions {
  viewportWidth: number;
  css?: string;
  mode?: 'flat' | 'byRow' | 'simple' | 'full';
}

export interface ParseResultWithDiagnostics<T> {
  success: boolean;
  data?: T;
  errors?: string[];
  warnings?: string[];
  metrics?: {
    parseTime: number;
    characterCount: number;
    totalTime: number;
    charsPerSecond: number;
  };
}

// Environment detection
export type Environment = 'web' | 'worker' | 'node' | 'unknown';